#Laboratorio sobre el manejo de "end" y "sep"
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print()

print("    *", "   * *", "  *   *", " *     *", "***   ***", sep="\n")
print("  *   *","  *   *","  *****", sep="\n")
print()

print("    *     " * 2)
print("   * *    " * 2)
print("  *   *   " * 2)
print(" *     *  " * 2)
print("***   *** " * 2)
print("  *   *   " * 2)
print("  *   *   " * 2)
print("  *****   " * 2)
print()

print('"Estoy"','"aprendiendo"\"','\""Python"\"',sep='\n"',end='"\n')